export const PROCESS_ENV = {
  DB_USERNAME:'lequochuypy1998',
  DB_PASSWORD:'aVk297UzRdSBlGNo',
  DB_NAME : 'twitter',
  JWT_SECRET_ACCESS_TOKEN :'lequochuy1998',
  JWT_SECRET_REFRESH_TOKEN:'lequochuy',
 
  
  DB_USERS_COLLECTION_NAME :'users',
  DB_REFRESH_TOKEN_COLLECTION_NAME :'refreshTokens',
  DB_FOLLOWER_COLLECTION_NAME : 'followers',
  REFRESH_TOKEN_EXPIRES_IN:'100d',
  ACCESS_TOKEN_EXPIRES_IN:'15m',
  VERIFY_EMAIL_TOKEN_EXPIRES_IN:'7d',
  JWT_SECRET_EMAIL_VERIFY_TOKEN : 'lequochuy10181998',
  VERIFY_FORGOT_PASSWORD_TOKEN_EXPIRES_IN : '5m',
  JWT_SECRET_FORGOT_PASSWORD_VERIFY_TOKEN: 'lequochuy2023'

 
}